package com.creamcheese.crackers.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
	/* Common */
	// Basic - C0***
	RUNTIME_EXCEPTION(BAD_REQUEST, "C0001", "RUNTIME_EXCEPTION"),
	METHOD_NOT_ALLOWED(BAD_REQUEST, "C0002", "METHOD_NOT_ALLOWED"),

	BAD_DATE_REQUEST(BAD_REQUEST, "C1003", "BAD_DATE_REQUEST"),

	// User - C2***
	LOGINID_DUPLICATE(CONFLICT, "C2002", "DUPLICATE_LOGINID_EXISTS"),
	ACCOUNT_NOT_FOUND(NOT_FOUND, "C2003", "USER_NOT_FOUND"),
	PASSWORD_NOT_MATCH(BAD_REQUEST, "C2004", "PASSWORD_NOT_MATCH"),
	PASSWORDS_NOT_EQUAL(BAD_REQUEST, "C2006", "PASSWORDS_NOT_EQUAL"),
	CERTIFICATION_CODE_NOT_MATCH(BAD_REQUEST, "C2007", "CERTIFICATIONCODE_NOT_MATCH"),

	// TOKEN - E1***
//	TOKEN_VALIDATE_FAILURE(BAD_REQUEST, "E1001", "INVALID_TOKEN"),
//	REFRESHTOKEN_EXPIRED(BAD_REQUEST, "E1002", "REFRESHTOKEN_EXPIRED"),

	INVALID_REFRESH_TOKEN(BAD_REQUEST, "E1001", "유효하지 않은 Refresh Token입니다."),
	INVALID_ACCESS_TOKEN(BAD_REQUEST, "E1002","유효하지 않은 Access Token입니다."),
	INVALID_AUTH_TOKEN(UNAUTHORIZED, "E1003","권한 정보가 없는 토큰입니다."),
	REFRESH_TOKEN_NOT_FOUND(NOT_FOUND, "E1004","로그아웃된 사용자입니다."),
	USER_NOT_FOUND(NOT_FOUND, "E1005","해당 정보의 사용자를 찾을 수 없습니다."),
	INVALID_UPDATE_PERIOD(BAD_REQUEST, "E1006","회원정보 수정은 30에 한번씩 가능합니다."),

	// WORKSPACE - E2***
	WORKSPACE_NOT_FOUND(NOT_FOUND, "E2001", "WORKSPACE_NOT_FOUND"),

	// WORKHISTORY - E3***
	WORKHISTORY_NOT_FOUND(NOT_FOUND, "E3001", "WORKHISTORY_NOT_FOUND"),

	// USERCARD - E4***
	USERCARD_NOT_FOUND(NOT_FOUND, "E4001", "USERCARD_NOT_FOUND"),
	USERCARD_ALREADY_EXISTS(BAD_REQUEST, "E4002", "이미 생성된 유저카드가 존재합니다."),
	USERCARD_NOT_EXISTS(NOT_FOUND, "E4003", "생성된 유저카드가 없습니다."),


	// CARD - E5***
	CARD_NOT_FOUND(NOT_FOUND, "E5001", "CARD_NOT_FOUND"),

	//SUCCESS
	LOGOUT_SUCCESS(OK, "S0001", "LOGOUT_SUCCESS");

	private final HttpStatus status;
	private final String code;
	private final String message;
}
