name: coinTalk chatRoom server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: cointalk-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create application-secret.yml
      run: |
        # application-secret.yml 생성
        touch ./src/main/resources/application-secret.yml 
        
        # Secrets의 APPLICATION_SECRET 값을 application-secret.yml에 쓰기
        echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml
        
    - name: Build with Gradle
      run: ./gradlew clean build
